from __future__ import annotations

from agent_libos.images import build_default_images
from agent_libos.modules.context import ModuleContext
from agent_libos.tools.builtin import (
    ActivateSkillTool,
    AskHumanTool,
    AppendMemoryObjectTool,
    CallJsonRpcMethodTool,
    CommitCheckpointToImageTool,
    CreateCheckpointTool,
    CreateMemoryNamespaceTool,
    CreateMemoryObjectTool,
    CreateObjectFromFileTool,
    DeleteDirectoryTool,
    DeleteFileTool,
    DelegateCapabilityTool,
    DiffCheckpointTool,
    DiscoverSkillsTool,
    EchoTool,
    ExecProcessTool,
    ForkCheckpointTool,
    ForkChildProcessTool,
    GetCurrentTimeTool,
    GetWorkingDirectoryTool,
    HumanOutputTool,
    InspectCapabilityTool,
    InspectCheckpointTool,
    InspectJsonRpcEndpointTool,
    ListCapabilitiesTool,
    ListCheckpointsTool,
    ListChildProcessesTool,
    ListJsonRpcEndpointsTool,
    ListMemoryNamespaceTool,
    LoadImageFromYamlTool,
    MergeChildMemoryTool,
    ParsePytestLogTool,
    ProcessExitTool,
    ProposeJitTool,
    ReadDirectoryTool,
    ReadMemoryObjectTool,
    ReadSkillResourceTool,
    ReadProcessMessagesTool,
    ReceiveProcessMessagesTool,
    ReadTextFileTool,
    RegisterJitTool,
    RequestPermissionTool,
    RestoreCheckpointTool,
    RevokeCapabilityTool,
    RunShellCommandTool,
    SendProcessMessageTool,
    SetWorkingDirectoryTool,
    SignalChildProcessTool,
    SleepTool,
    SpawnChildProcessTool,
    UnloadSkillTool,
    ValidateJitTool,
    WaitChildProcessTool,
    WriteDirectoryTool,
    WriteObjectToFileTool,
    WriteTextFileTool,
)


def register_module(ctx: ModuleContext) -> None:
    """Register the built-in Agent libOS tools and default images."""

    for tool in [
        EchoTool(),
        ExecProcessTool(),
        GetCurrentTimeTool(),
        SleepTool(),
        ParsePytestLogTool(),
        AppendMemoryObjectTool(),
        CreateCheckpointTool(),
        CreateMemoryNamespaceTool(),
        CreateMemoryObjectTool(),
        CreateObjectFromFileTool(),
        DeleteDirectoryTool(),
        DeleteFileTool(),
        DelegateCapabilityTool(),
        DiffCheckpointTool(),
        DiscoverSkillsTool(),
        ActivateSkillTool(),
        ForkChildProcessTool(),
        ForkCheckpointTool(),
        GetWorkingDirectoryTool(),
        LoadImageFromYamlTool(),
        ListChildProcessesTool(),
        ListMemoryNamespaceTool(),
        MergeChildMemoryTool(),
        ProcessExitTool(),
        ProposeJitTool(),
        RequestPermissionTool(),
        ReadDirectoryTool(),
        ReadMemoryObjectTool(),
        ReadProcessMessagesTool(),
        ReceiveProcessMessagesTool(),
        ReadTextFileTool(),
        RegisterJitTool(),
        SignalChildProcessTool(),
        SetWorkingDirectoryTool(),
        SpawnChildProcessTool(),
        ValidateJitTool(),
        WriteObjectToFileTool(),
        WriteDirectoryTool(),
        WriteTextFileTool(),
        AskHumanTool(),
        HumanOutputTool(),
        CallJsonRpcMethodTool(),
        CommitCheckpointToImageTool(),
        InspectCapabilityTool(),
        InspectCheckpointTool(),
        InspectJsonRpcEndpointTool(),
        ReadSkillResourceTool(),
        WaitChildProcessTool(),
        ListCapabilitiesTool(),
        ListCheckpointsTool(),
        ListJsonRpcEndpointsTool(),
        RunShellCommandTool(),
        RevokeCapabilityTool(),
        RestoreCheckpointTool(),
        SendProcessMessageTool(),
        UnloadSkillTool(),
    ]:
        ctx.register_tool(tool)

    for image in build_default_images(ctx.runtime.config).values():
        ctx.register_image(image)
